# Copyright (c) 2025 Z5Labs and Contributors
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

openapi:
  title: Problem Details Example API
  version: v1.0.0
